version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: finsight_postgres
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: finsight_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Run API locally
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finsight_api
    environment:
      ENVIRONMENT: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: finsight_dev
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app/api
      - ./src:/app/src
      - ./config.py:/app/config.py
    command: python -m flask --app api.main run --host 0.0.0.0 --port 5000 --debug

volumes:
  postgres_data:

